# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5848f2a2a41f45510de6ef74b6a7aa2c"
name = "INKA Production"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
